apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: fortio-deploy
spec:
  template:
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: fortio
        spec:
          containers:
          - name: fortio
            image: istio/fortio:latest_release
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
              name: http-fortio
            - containerPort: 8079
              name: grpc-ping
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeploymentPlacement
metadata:
  name: fortio-deploy
spec:
  clusterNames:
  - cluster2
  - cluster1