apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedRouteRule
metadata:
  name: httpbin-default-v1
spec:
  template:
    spec:
      destination:
        name: httpbin
      precedence: 1
      route:
      - labels:
          version: v1
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedRouteRulePlacement
metadata:
  name: httpbin-default-v1
spec:
  clusterNames:
  - cluster2
  - cluster1