apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServiceAccount
metadata:
  name: sleep
spec:
  template:
    automountServiceAccountToken: true
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServiceAccountPlacement
metadata:
  name: sleep
spec:
  clusterNames:
  - cluster2
  - cluster1
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  template:
    spec:
      ports:
      - port: 80
        name: http
      selector:
        app: sleep
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  clusterNames:
  - cluster1
  - cluster2
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: sleep
spec:
  template:
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: sleep
      template:
        metadata:
          labels:
            app: sleep
        spec:
          serviceAccountName: sleep
          containers:
          - name: sleep
            image: pstauffer/curl
            command: ["/bin/sleep", "3650d"]
            imagePullPolicy: IfNotPresent
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedDeploymentPlacement
metadata:
  name: sleep
spec:
  clusterNames:
  - cluster1
  - cluster2