apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: federation-system
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:v0.5.7
        args:
        - --source=crd
        - --crd-source-apiversion=multiclusterdns.federation.k8s.io/v1alpha1
        - --crd-source-kind=DNSEndpoint
        - --provider=google
        # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available zones.
        - --domain-filter=foo.com
        - --registry=txt
        - --txt-prefix=cname
        - --txt-owner-id=change_me
        #- --policy=upsert-only # Prevents ExternalDNS from deleting any records, omit to enable full synchronization
