apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: Domain
metadata:
  name: external
  namespace: federation-system
domain: external.daneyon.com
---
apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: ServiceDNSRecord
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  domainRef: external
  dnsPrefix: httpbin
  recordTTL: 300
