apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  template:
    spec:
      ports:
      - name: http
        port: 8000
      selector:
        app: httpbin
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  clusterNames:
  - cluster2
  - cluster1
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: httpbin
spec:
  template:
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: httpbin
          version: v1
      template:
        metadata:
          labels:
            app: httpbin
            version: v1
        spec:
          containers:
          - image: docker.io/citizenstig/httpbin
            imagePullPolicy: IfNotPresent
            name: httpbin
            ports:
            - containerPort: 8000
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedDeploymentPlacement
metadata:
  name: httpbin
spec:
  clusterNames:
  - cluster2
  - cluster1